import * as XLSX from "xlsx";
import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
} from "docx";
import jsPDF from "jspdf";

interface ExportRow {
  [key: string]: string | number | undefined;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportExcel(rows: ExportRow[], filename: string, sheetName = "Sheet1") {
  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  XLSX.writeFile(wb, `${filename}.xlsx`);
}

export async function exportWord(
  title: string,
  rows: ExportRow[],
  filename: string
) {
  if (rows.length === 0) {
    return;
  }
  const headers = Object.keys(rows[0]);
  const headerRow = new TableRow({
    children: headers.map(
      (h) =>
        new TableCell({
          shading: { fill: "F97316" },
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 }),
              ],
            }),
          ],
        })
    ),
  });
  const dataRows = rows.map(
    (r) =>
      new TableRow({
        children: headers.map(
          (h) =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: String(r[h] ?? ""), size: 18 })] })],
            })
        ),
      })
  );
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.LEFT,
            children: [new TextRun({ text: title, bold: true, size: 32, color: "1E3A8A" })],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by i-Tamil Recruit · ${new Date().toLocaleString()}`,
                italics: true,
                size: 16,
                color: "6B7280",
              }),
            ],
          }),
          new Paragraph({ children: [new TextRun({ text: " " })] }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [headerRow, ...dataRows],
            borders: {
              top: { style: BorderStyle.SINGLE, size: 4, color: "E4E4E7" },
              bottom: { style: BorderStyle.SINGLE, size: 4, color: "E4E4E7" },
              left: { style: BorderStyle.SINGLE, size: 4, color: "E4E4E7" },
              right: { style: BorderStyle.SINGLE, size: 4, color: "E4E4E7" },
              insideHorizontal: { style: BorderStyle.SINGLE, size: 2, color: "F4F4F5" },
              insideVertical: { style: BorderStyle.SINGLE, size: 2, color: "F4F4F5" },
            },
          }),
        ],
      },
    ],
  });
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, `${filename}.docx`);
}

export function exportSummaryPdf(title: string, rows: ExportRow[], filename: string) {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(30, 58, 138);
  pdf.setFontSize(20);
  pdf.text(title, 40, 50);

  pdf.setFont("helvetica", "italic");
  pdf.setTextColor(107, 114, 128);
  pdf.setFontSize(10);
  pdf.text(`Generated ${new Date().toLocaleString()} · i-Tamil Recruit`, 40, 70);

  if (rows.length === 0) {
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(0, 0, 0);
    pdf.text("No records.", 40, 100);
    pdf.save(`${filename}.pdf`);
    return;
  }

  const headers = Object.keys(rows[0]);
  const startY = 95;
  const startX = 40;
  const colWidth = 515 / headers.length;
  const rowHeight = 22;

  // Header
  pdf.setFillColor(249, 115, 22);
  pdf.rect(startX, startY, 515, rowHeight, "F");
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(9);
  headers.forEach((h, i) => {
    pdf.text(h, startX + i * colWidth + 6, startY + 14);
  });

  // Rows
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(20, 20, 20);
  let y = startY + rowHeight;
  rows.forEach((r, idx) => {
    if (idx % 2 === 0) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(startX, y, 515, rowHeight, "F");
    }
    headers.forEach((h, i) => {
      const text = String(r[h] ?? "");
      pdf.text(text.length > 28 ? text.slice(0, 25) + "…" : text, startX + i * colWidth + 6, y + 14);
    });
    y += rowHeight;
    if (y > 770) {
      pdf.addPage();
      y = 50;
    }
  });

  pdf.save(`${filename}.pdf`);
}
